
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "arthurguyader"
    reviewers:
      - "omnis-org/omnis-ui"
